[package]
name = "power_flow_data"
version = "0.1.0"
description = "RAW power flow data file parser"
repository = "https://github.com/rwl/power_flow_data"
license = "MIT"
edition = "2021"

[dependencies]
arrayvec = "0.7"
enum_common_fields = "0.7"